# ###################
# Gradle Properties
# ###################
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=true

# Uncomment it if you want to know the details of build process.
# More recommended to set it locally rather than project sharing.
#org.gradle.logging.level=info

# Uncomment it if you want the console to look prettier.
# More recommended to set it locally rather than project sharing.
#org.gradle.console=rich

# Use results of the first build during the configuration phase if the build environment remains unchanged,
# which will quickly entering the execution phase and accelerating the overall build process.
# Feel free to disable (comment) it if something go wrong.
org.gradle.configuration-cache=true

# ###################
# Project & Mod Properties
# ###################
group=me.ctidy.mcmod.ftb.ultimine.indicator
mod_version=1.1.0

archives_base_name=ftb-ultimine-indicator-unofficial

mod_id=ftbultimine_indicator
mod_name=FTB Ultimine Indicator

description=A more intuitive indicator for FTB Ultimine.

license=LGPL-v3-or-later
credits=

author=Tidy-Bear, Polaris_Light

# ###################
# MC & Common API Properties
# ###################
java_version=21
minecraft_version=1.21.1

# https://github.com/neoforged/ModDevGradle?tab=readme-ov-file#better-minecraft-parameter-names--javadoc-parchment
# https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

mixin_version=0.8.5
mixin_extras_version=0.4.1

resourcepack_format=34
datapack_format=57

neo_version=21.1.248
neo_version_range=[21.1.0,)
loader_version_range=[4,)
minecraft_version_range=[1.21.1,)
ftb_library_version=2101.1.28
ftb_ultimine_version=2101.1.15
ftb_ultimine_version_range=[2101.1.15,)
